[browser]
background = "#1a1a1a"
border = "#4c4c4e"

[search_prompt]
background = "#1a1a1a"
border = "#545454"
division = "#313131"

[search_prompt.input]
text = "#eaeaea"

[search_prompt.result_item]
text = "#bfbfbf"
text_url = "#545454"

[search_prompt.result_item.selected]
background = "#2d2d2d"
text = "#ffffff"
text_url = "#828282"

[link_badge]
background = "#010101"
border = "#323232"
text = "#a9a9a9"
